### ISSUE TITLE
运行 build 和 serve 时出错

### ISSUE THREAD

**Issue by Skywt2003** [ksky521/nodeppt#230]
| Executable | Version |
| ---: | :--- |
| `node --version` | v10.15.3 |
| `npm --version`  | 6.4.1 |
| `nodeppt -v` | 2.1.5 |

| OS | Version |
| --- | --- |
| CentOS | 7.6 |

运行 `nodeppt build slide.md` 或者 `nodeppt serve slide.md` 均出现如下错误：

```
 error  in /usr/lib/node_modules/nodeppt/node_modules/nodeppt-js/assets/scss/full.scss

Module build failed (from /usr/lib/node_modules/nodeppt/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from /usr/lib/node_modules/nodeppt/node_modules/sass-loader/lib/loader.js):
Error: Missing binding /usr/lib/node_modules/nodeppt/node_modules/node-sass/vendor/linux-x64-64/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/usr/lib/node_modules/nodeppt/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/usr/lib/node_modules/nodeppt/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/usr/lib/node_modules/nodeppt/node_modules/sass-loader/lib/loader.js:46:72)
    at runLoaders (/usr/lib/node_modules/nodeppt/node_modules/webpack/lib/NormalModule.js:301:20)
    at /usr/lib/node_modules/nodeppt/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/lib/node_modules/nodeppt/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/usr/lib/node_modules/nodeppt/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/usr/lib/node_modules/nodeppt/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/lib/node_modules/nodeppt/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/lib/node_modules/nodeppt/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/usr/lib/node_modules/nodeppt/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /usr/lib/node_modules/nodeppt/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

 @ /usr/lib/node_modules/nodeppt/node_modules/nodeppt-js/index.js 2:0-33
 @ /usr/lib/node_modules/nodeppt/node_modules/nodeppt-serve/template/main.js
 @ multi /usr/lib/node_modules/nodeppt/node_modules/nodeppt-serve/template/main.js
```

按照提示运行 `npm rebuild node-sass` 后仍然没有解决问题；重装 node.js 和 npm 问题也仍然存在。

在另一台 Ubuntu 下也出现了类似问题：

| Executable | Version |
| ---: | :--- |
| `node --version` | v10.15.3 |
| `npm --version`  | 6.9.1-next.0 |
| `nodeppt -v` | 2.1.5 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 LTS |

**Comment by ksky521** [comment]
没有安装node-sass，在重新npm install -g nodeppt 保证没有错误，如果不行试下cnpm，sass包需要编译的

**Comment by Skywt2003** [comment]
我好像是装了 node-sass 的……重新 `npm install -g nodeppt` 后仍然错误，显示如下信息：
```
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v10.15.3/lib/node_modules/nodeppt/node_modules/node-sass/build'
gyp ERR! System Linux 4.10.4-1.el7.elrepo.x86_64
gyp ERR! command "/root/.nvm/versions/node/v10.15.3/bin/node" "/root/.nvm/versions/node/v10.15.3/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/.nvm/versions/node/v10.15.3/lib/node_modules/nodeppt/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/nodeppt/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-31T04_50_22_439Z-debug.log
```

**Comment by ksky521** [comment]
permission denied, 这是没有权限呢

**Comment by Skywt2003** [comment]
但是我是以root用户运行的呢……

**Comment by leoljustsave** [comment]
我也出现了相同的问题，提示 rebuild node-sass，输了也无效，请问解决了么

**Comment by Skywt2003** [comment]
没解决……

**Comment by ksky521** [comment]
再试下重新安装下依赖，这是node 版本不一致导致的，你可能升级了 node 版本，但是 sass 没有重新编译

**Comment by ChaseChan** [comment]
+1 重新安装过了也无效

**Comment by Leowuqunqun** [comment]
删除sass 相关的包 重新安装 解决问题

**Comment by Skywt2003** [comment]
问题解决了，参考 https://segmentfault.com/a/1190000012912618 重装 node-sass，安装时都加上 `--unsafe-perm` 即可……

**Comment by Skywt2003** [comment]
解决了，参考 https://segmentfault.com/a/1190000012912618 ，root 身份安装 npm 包的时候都要加上 `--unsafe-perm` ……

**Comment by guguji5** [comment]
执行 sudo npm install -g nodeppt  一直报错。npm rebuild node-sass和sudo npm install -g --unsafe-perm node-sass都试过了。放弃了
```
sudo npm install -g nodeppt 

......
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/didi/PPT/node_modules/node-sass/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/didi/PPT/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/didi/PPT/node_modules/node-sass
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open '/Users/didi/PPT/package.json'
npm WARN PPT No description
npm WARN PPT No repository field.
npm WARN PPT No README data
npm WARN PPT No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/didi/.npm/_logs/2019-11-05T08_41_16_967Z-debug.log
➜  PPT ls
node_modules
➜  PPT node -v
v8.12.0
➜  PPT npm -v
6.4.1
```

**Comment by Skywt2003** [comment]
总感觉每次用 `npm` 都会有一大堆错误……

**Comment by ksky521** [comment]
使用新版，去掉 node-sass 了
