### ISSUE TITLE
Cannot install: permission denied (not using sudo)

### ISSUE THREAD

**Issue by sebelk** [ksky521/nodeppt#242]
| Executable | Version |
| ---: | :--- |
| `node --version` | v10.15.3 |
| `npm --version`  | 6.4.1 |
| `nodeppt -v` | could not install |

| OS | Version |
| --- | --- |
| Fedora | 30 |

After running `npm install -g nodeppt` as root it outputs:

```
/usr/bin/nodeppt -> /usr/lib/node_modules/nodeppt/bin/nodeppt

> node-sass@4.11.0 install /usr/lib/node_modules/nodeppt/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/nodeppt/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/nodeppt/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:752:3)
    at sync (/usr/lib/node_modules/nodeppt/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/nodeppt/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/nodeppt/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/lib/node_modules/nodeppt/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/usr/lib/node_modules/nodeppt/node_modules/node-sass/vendor' }

> node-sass@4.11.0 postinstall /usr/lib/node_modules/nodeppt/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /usr/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:13:12)\n    at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:19)\n    at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)\n    at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16\n    at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5\n    at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:13:12)\n    at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:19)\n    at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)\n    at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16\n    at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5\n    at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/nodeppt/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/nodeppt/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/nodeppt/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/nodeppt/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/nodeppt/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/nodeppt/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 5.0.9-301.fc30.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/nodeppt/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/nodeppt/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-02T14_29_15_164Z-debug.log
```

Permissions:

```
ls -ld /usr/lib/node_modules/
drwxr-xr-x 19 root root 4096 may  2 11:33 /usr/lib/node_modules
```

Any idea?

Thanks in advance!

**Comment by Shakabrahh** [comment]
Solved the problem with:
`npm install -g nodeppt --unsafe-perm=true --allow-root`
