### ISSUE TITLE
nodeppt 安装时错误，以管理员身份运行时显示权限不够

### ISSUE THREAD

**Issue by BlueDone** [ksky521/nodeppt#283]
| Executable | Version |
| ---: | :--- |
| `node --version` | v12.14.0 |
| `npm --version`  | 6.13.6 |
| `nodeppt -v` | command not found: nodeppt |

| OS | Version |
| --- | --- |
| Ubuntu | 19.10 |

我是使用 ```sudo npm install -g nodeppt``` 指令安装的

我在安装 ```nodeppt``` 时出现了一些故障：

```bash
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/nodeppt/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-13T13_36_13_857Z-debug.log

```

不知道该怎么解决，好像不是权限问题，而是部分关键文件被删去了。。。

请 ksky521 帮帮我。

下面是全部的安装信息：
```bash
$ sudo npm install -g nodeppt
[sudo] bluedone 的密码： 
/opt/nodejs/bin/nodeppt -> /opt/nodejs/lib/node_modules/nodeppt/bin/nodeppt

> node-sass@4.12.0 install /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass
> node scripts/install.js

Unable to save binary /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/vendor/linux-x64-72 : Error: EACCES: permission denied, mkdir '/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:823:3)
    at sync (/opt/nodejs/lib/node_modules/nodeppt/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/opt/nodejs/lib/node_modules/nodeppt/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/vendor'
}

> ejs@2.7.4 postinstall /opt/nodejs/lib/node_modules/nodeppt/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> node-sass@4.12.0 postinstall /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass
> node scripts/build.js

Building: /opt/nodejs/bin/node /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/opt/nodejs/bin/node',
gyp verb cli   '/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.14.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.17
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.14.0
gyp verb command install [ '12.14.0' ]
gyp verb install input version string "12.14.0"
gyp verb install installing version: 12.14.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/12.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '12.14.0' ]
gyp verb install input version string "12.14.0"
gyp verb install installing version: 12.14.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 12.14.0
gyp verb ensuring nodedir is created /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/.node-gyp/12.14.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '12.14.0' ]
gyp verb remove using node-gyp dir: /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 12.14.0
gyp verb remove removing development files for version: 12.14.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '12.14.0' ]
gyp verb remove using node-gyp dir: /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 12.14.0
gyp verb remove removing development files for version: 12.14.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/nodejs/lib/node_modules/nodeppt/node_modules/node-sass
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/nodeppt/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-13T13_36_13_857Z-debug.log
```

**Comment by BlueDone** [comment]
若不以管理员身份运行：
```bash
$ npm install -g nodeppt
npm WARN checkPermissions Missing write access to /opt/nodejs/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /opt/nodejs/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/opt/nodejs/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/opt/nodejs/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/opt/nodejs/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/nodejs/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bluedone/.npm/_logs/2020-01-13T13_49_06_287Z-debug.log
```

**Comment by ksky521** [comment]
使用新版，去掉 node-sass 了
