### ISSUE TITLE
nodeppt build slide.md 报错

### ISSUE THREAD

**Issue by coolxv** [ksky521/nodeppt#305]
| Executable | Version |
| ---: | :--- |
| `node --version` | v17.6.0 |
| `npm --version`  | 8.5.3|
| `nodeppt -v` | 2.2.2|

| OS | Version |
| --- | --- |
| Windows 11 | 21H2|

```
Node.js v17.6.0

C:\Users\lenovo\Desktop\mark-markdown-ppt>
C:\Users\lenovo\Desktop\mark-markdown-ppt>nodeppt build slide.md
 INFO  Build ...
10% building 1/1 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
10% building 1/2 modules 1 active ...pData\Roaming\npm\node_modules\nodeppt\node_modules\nodeppt-serve\template\main.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\nodeppt\node_modules\babel-loader\lib\index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.6.0
```

**Comment by coolxv** [comment]
set NODE_OPTIONS=--openssl-legacy-provider

可用

**Comment by Juminiy** [comment]
Thanks,Linux 上也是这个问题。
